# Generated by Django 5.1.1 on 2024-09-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('turnStart', 'Turn Start'), ('hero', 'Hero'), ('movement', 'Movement'), ('shooting', 'Shooting'), ('charge', 'Charge'), ('combat', 'Combat'), ('turnEnd', 'Turn End'), ('passive', 'Passive'), ('reaction', 'Reaction')], max_length=10)),
                ('side', models.CharField(choices=[('your', 'Your'), ('enemy', 'Enemy'), ('any', 'Any')], max_length=5)),
                ('phaseText', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('declare', models.TextField(null=True)),
                ('effect', models.TextField()),
                ('lore', models.TextField(null=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warscroll',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('wounds', models.IntegerField()),
                ('move', models.IntegerField()),
                ('control', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('wards', models.IntegerField(null=True)),
                ('baseSize', models.IntegerField()),
                ('points', models.IntegerField()),
                ('numberOfModels', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='warscroll.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('warscroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='warscroll.warscroll')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='warscroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='warscroll.warscroll'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isRange', models.BooleanField(max_length=50)),
                ('range', models.IntegerField(null=True)),
                ('attack', models.CharField(max_length=5)),
                ('hit', models.IntegerField()),
                ('wound', models.IntegerField()),
                ('rend', models.IntegerField()),
                ('damage', models.CharField(max_length=3)),
                ('warscroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='warscroll.warscroll')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='warscroll.weapon')),
            ],
        ),
    ]
