# Generated by Django 5.1.1 on 2024-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warscroll', '0002_warscroll_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warscroll',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
